# Use Node.js image to build the Angular app
FROM node:18 AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --configuration production

# Use Nginx to serve the Angular app
FROM nginx:alpine
COPY --from=build /app/dist/* /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
